#!/bin/sh

# Set defaults if not provided
: "${SUPABASE_URL:=https://cpisbazpqkrdzxcacvpq.supabase.co}"
: "${SUPABASE_ANON_KEY:=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwaXNiYXpwcWtyZHp4Y2FjdnBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUzOTkwMTYsImV4cCI6MjA5MDk3NTAxNn0.XjanUAUC84zPzAErQ__Wz-jOyPJnh73e2tu5AM4RHaU}"

# Inject into config.js
cat <<EOF > /usr/share/nginx/html/js/config.js
/**
 * Auto-generated by docker-entrypoint.sh
 */
window.HMS_CONFIG = {
    SUPABASE_URL: "${SUPABASE_URL}",
    SUPABASE_ANON_KEY: "${SUPABASE_ANON_KEY}"
};
EOF

echo "Injected environment variables into js/config.js"

# Execute the original CMD
exec "$@"
